#!/bin/bash

# setup XIM environment for fcitx
export XMODIFIERS="@im=fcitx"
export XIM=fcitx
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export XIM_PROGRAM=fcitx
fcitx &

# start the desktop environment

# for GNOME
#exec ck-launch-session gnome-session

# for LXDE
exec ck-launch-session startlxde
